In [17]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [18]:
class Layer():
    
    def __init__(self,no_of_neurons,previous_layer=None,activation=None,name='def'):
        # number of neurons in current layer
        self.n = no_of_neurons
        # layer that sends input into this layer
        self.previous_layer = previous_layer
        # layer that recieves this layer's output
        self.next_layer = None
        if (self.previous_layer is not None):
            # sort the hierarchy
            previous_layer.next_layer = self
            # initialize the weights between the layers
            previous_layer.initialize_weights()
            # set the activation function
            self.set_activation(activation)
        else:
            # this is the input layer
            self.set_activation('none')
        # for testing purposes
        self.name = name
    
    def initialize_weights(self):
        if (self.next_layer is not None):
            # weights
            self.weights = np.random.normal(0,0.1,(self.n,self.next_layer.n))
            # bias separately
            self.bias = np.random.normal(0,0.1,self.next_layer.n)
    
    def set_activation(self,func='ReLU'):
        if (func=='ReLU'):
            # set ReLU and the derivative
            self.func = ReLU
            self.deriv = dReLU
        if (func=='sigmoid'):
            self.func = sigmoid
            self.deriv = dSigmoid
        elif (func=='none'):
            self.func = lambda x:x
            self.deriv = lambda x:1

    def feed_forward(self,z):
        # remember z and a for later
        self.z = z
        self.a = self.func(z)
        if (self.next_layer is not None):
            return self.next_layer.feed_forward(self.a @ self.weights + self.bias)
        else:
            return self.a
    
    def update_weights(self,learning_rate,error):
        self.weights -= self.weights*learning_rate*error
        self.bias -= self.bias*learning_rate*error
        
    def back_propagate(self,y=None,learning_rate=0.00001):       
        if (self.next_layer is None):
            self.error = self.a - y
            self.delta = self.error * self.deriv(self.z)
        else:
            # removed the .T from weights
            self.error = self.weights @ self.next_layer.delta
            self.delta = self.error * self.deriv(self.z)
            for i in range (self.weights.shape[1]):
                self.weights[:,i] -= learning_rate * (self.a * self.next_layer.delta[i])
            for i in range(len(self.bias)):
                self.bias[i] -= learning_rate * self.next_layer.delta[i]
        if (self.previous_layer is not None):
            self.previous_layer.back_propagate(learning_rate=learning_rate)
        
def ReLU(x):
    # ReLU function
    return np.maximum(x,0)

def dReLU(x):
    x = x.copy()
    x[x<=0] = 0
    x[x>0] = 1
    return x   

def sigmoid(x):
    return 1/(np.exp(-x)+1)

def dSigmoid(x):
    s = sigmoid(x)
    return s*(1-s)

In [1]:
import neural_network

In [32]:
size = 300
r = 6
# blob 1
x = np.random.normal(4,2,(size))
y = np.random.normal(1,2,(size))
# blob 2
x2 = np.zeros(size)
y2 = np.zeros(size)
for i in range(size):
    x2[i] = 4+r*math.cos(2*math.pi*(i/size))# + 
    y2[i] = 1+r*math.sin(2*math.pi*(i/size))# + 
x2+=np.random.normal(0,1.5,(size))
y2+=np.random.normal(0,1.5,(size))

x = np.concatenate((x,x2))
y = np.concatenate((y,y2))
# add xy together 
X = np.hstack((x,y)).reshape(2,2*size).T
# reuse y for flags
y[:size] = 1
y[size:] = 0

#shuffle
mask = np.random.permutation(len(X))
X = X[mask]
y = y[mask]

In [33]:
a = Layer(2,name='a')

In [34]:
b = Layer(8,a,activation='ReLU',name='b')

In [35]:
c = Layer(1,b,activation='sigmoid',name='c')

In [25]:
a.feed_forward(X[500])

array([0.52716674])

In [26]:
a.feed_forward(x[0:2])

array([0.52576323])

In [37]:
for i in range(20000):
    x = np.random.random(size=2)
    y = np.array([x[0],x[1],x[0]+x[1],x[0]-x[1],x[0]*x[1],3*x[0]-1.6*x[1]])
    a.feed_forward(x)
    c.back_propagate(y,learning_rate=0.0001)

ValueError: shapes (8,1) and (6,) not aligned: 1 (dim 1) != 6 (dim 0)

In [734]:
x = np.array([0.99,0.67])
y = np.array([x[0],x[1],x[0]+x[1],x[0]-x[1],x[0]*x[1],3*x[0]-1.6*x[1]])
(a.feed_forward(x) - y).mean()

-0.022158165238907568

In [735]:
y

array([0.99  , 0.67  , 1.66  , 0.32  , 0.6633, 1.898 ])

In [737]:
np.round(a.feed_forward(x),2)

array([0.99, 0.64, 1.64, 0.33, 0.55, 1.9 ])

In [603]:
a.feed_forward(x)

array([0.99617295, 0.67346865, 1.66621645, 0.32224475, 0.57991196])

In [11]:
test = np.array([-0.99617295, 0.67346865, -1.66621645, 0.32224475, -0.57991196])

In [12]:
test

array([-0.99617295,  0.67346865, -1.66621645,  0.32224475, -0.57991196])

In [16]:
dSigmoid(test)

array([0.19695939, 0.22366539, 0.13367076, 0.24362059, 0.2301057 ])

In [1]:
import numpy as np

In [3]:
np.random.normal(0, 0, 100)

TypeError: normal() got an unexpected keyword argument 'dtype'