# Naive Bayes Classification

In [1]:
import numpy as np
import math

from naive_bayes import NaiveBayes

### Generate data

In [2]:
size =1000

# training set
coefficients = [0.5,-1.4,2.1,-3,10.4,-8]
X = np.ones((size,len(coefficients)))
for i in range(0,len(coefficients)):
    X[:,i]=np.random.rand(size)
y = np.vectorize(lambda x: (1/(1+math.exp(-x))))
y = y((X*coefficients).sum(axis=1) + np.random.normal(size=size))
y = np.vectorize(lambda x: round(x*2))(y)

# test set
X_test = np.ones((size,len(coefficients)))
for i in range(1,len(coefficients)):
    X_test[:,i]=np.random.rand(size)
y_test = np.vectorize(lambda x: (1/(1+math.exp(-x))))
y_test = y_test((X_test*coefficients).sum(axis=1) + np.random.normal(size=size))
y_test = np.vectorize(lambda x: round(x*2))(y_test)

In [3]:
# check balance for training set
np.unique(y,return_counts=True)[1]

array([372, 192, 436])

In [4]:
# chack balance for test set
np.unique(y_test,return_counts=True)[1]

array([347, 176, 477])

### Train model

In [5]:
nb = NaiveBayes()
nb.fit(X,y)

### Make predictions and assess model

In [6]:
pred = nb.predict(X_test)
pred[:10]

array([1., 0., 2., 2., 2., 2., 2., 1., 0., 1.])

**Total accuracy**

In [7]:
nb.score(X,y)

0.795

In [8]:
nb.score(X_test,y_test)

0.788